INSERT INTO vitrinis VALUES('A2 Style'
, 'A2 Style'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Conheça mais como mudar sua maneira de se vestir, com cores e modelos de roupas certos!
Faça a sua imagem aumentar o seu sucesso!'
, 'Moda'
, ''
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('ACG Advogados'
, 'ACG Advogados'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Advocacia'
, 'Serviços e Produtos'
, 'm.facebook.com/acciolicalenteegoto.advogados'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Adriana Maroquio - Fotografia'
, 'Adriana Maroquio - Fotografia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Fotógrafa de Gestantes, Famílias, Crianças e Bebês Newborn. A Fotografia é a melhor lembrança que você pode ter de cada momento de sua vida. No futuro elas contarão a sua história!!'
, 'Serviços e Produtos'
, 'www.adrianamaroquio.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Alessandra Scatena'
, 'Alessandra Scatena'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, ''
, 'Serviços e Produtos'
, 'm.facebook.com/alessandra.scatena.16'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Amandica Indica'
, 'Amandica Indica'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Amanda Accioli, Consultora em Eventos Sociais & Casamentos, Promoter, advogada na área de Direito de Família (Casamentos e Homoafetivos). Saibam mais acessando: www.amandicaindica.com.bre sigam-mewww.twitter.com/Amandica_Indica'
, 'Serviços e Produtos'
, 'www.amandicaindica.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Andréa Guimarães'
, 'Andréa Guimarães'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/andrea_guimaraes/andrea_guimaraes1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/andrea_guimaraes/andrea_guimaraes2.jpg'
, 'Produtora de eventos infantis e adultos, Andrea Guimarães é a preferida dos famosos, criando temas personalizados e transformando sonhos em eventos bem elaborados por todo o país.'
, 'Decoração de Festas'
, 'm.facebook.com/pages/Andrea-Guimaraes-Producoes-e-Eventos/194608023938914'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Atelier Caiu do Céu'
, 'Atelier Caiu do Céu'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Para Pequenos e grandes! Fadas, bailarinas, principes, princesas, móbiles para decorar com capricho e carinho'
, 'Serviços e Produtos'
, 'm.facebook.com/AtelierCaiuDoCeu'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('BarBarOz Bar & Bartenders'
, 'BarBarOz Bar & Bartenders'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/barbaroz_bar_&_bartenders/barbaroz_bar_&_bartenders1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/barbaroz_bar_&_bartenders/barbaroz_bar_&_bartenders2.jpg'
, 'Oferecemos o que há de melhor em coquetalaria nacional e internacional, com produtos e bartenders de qualidade, elevando sabor e aroma dos coquetéis elaborados ao mais alto patamar de qualidade e beleza dos coquetéis apresentados. Você também pode personalizar a sua festa.'
, 'Alimento e Bebida'
, 'm.facebook.com/BarBarOzBartenders'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Bearberry'
, 'Bearberry'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Acaba de nascer 
um espaço único e exclusivo... Um novo             
conceito em 
moda infantil, 
enxovais, acessórios, puericultura, brinquedos, móveis, decoração, diversão e atendimento especial reunidos em um só lugar......Venha conhecer a Bearberry!'
, 'Móveis'
, 'm.facebook.com/bearberry.store'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Buffet Arroz de Festa'
, 'Buffet Arroz de Festa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Banquetes em festas de casamento, aniversários e eventos corporativos. Aposta na culinária artesanal de bases clássicas, com pitadas de ousadia'
, 'Alimento e Bebida'
, 'www.arrozdefesta.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Buffet Santa Especiaria'
, 'Buffet Santa Especiaria'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Santa Especiaria Gastronomia é formada por profissionais que amam o que fazem, e está a sua disposição para superar suas expectativas, cozinhando ideias e encontrando o tempero certo para o seu evento!  Na cozinha criamos receitas diferenciadas com sabores surpreendentes, nas releituras de pratos tradicionais e contemporâneos.'
, 'Alimento e Bebida'
, 'www.santaespeciaria.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Cantinho de Artesã'
, 'Cantinho de Artesã'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/cantinho_de_artesa/cantinho_de_artesa1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/cantinho_de_artesa/cantinho_de_artesa2.jpg'
, 'Artesanatos'
, 'Serviços e Produtos'
, ''
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Celebrar com Festa'
, 'Celebrar com Festa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Especializada em Organização e Decoração de festas.Desenvolvemos festas exclusivas, personalizadas para eventos sociais e corporativos.Com experiência afirmo que detalhes fazem à verdadeira diferença, tornando a festa inesquecível! Confira!'
, 'Decoração de Festas'
, 'www.celebrarcomfesta.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Celebration'
, 'Celebration'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Celebration,a empresa organiza chás de bebês, maternidade, batizados e festas infantis. Com uma equipe qualificada e fornecedores de altíssimo padrão, cuidaremos de cada detalhe, para que cada ocasião, seja celebrada de forma única.'
, 'Decoração de Festas'
, 'www.dipendap.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Circo e Cia'
, 'Circo e Cia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Grupo de artistas que atua no teatro, em festas, escolas e eventos.
Bichos gigantes manipulados em perna de pau, palhaços, oficinas, performances, shows circenses e muito mais. Temos a experiência de mais de 20 anos de sucesso!!'
, 'Entretenimento'
, 'm.facebook.com/circocia'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Deni Leivas'
, 'Deni Leivas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Trabalho com projetos personalizados, acompanho o que as tendências nacionais e internacionais têm de melhor em decoração floral. Arranjos especiais são apresentados a cada evento, minha paixão pelas flores é demonstrada em minhas obras de artes florais, levando o requinte que seu evento merece.'
, 'Decoração de Festas'
, 'm.facebook.com/pages/Deni-Leivas/564827936869755'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dip en Dap'
, 'Dip en Dap'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Com uma equipe qualificada para atender aos mais diferentes gostos, a Dip en Dap possui móveis de design exclusivo, decoração, enxovais, porta-maternidade, lembrancinhas e presentes para a ocasião especial que é o nascimento de uma nova vida.'
, 'Móveis'
, 'www.dipendap.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Empório da Papinha'
, 'Empório da Papinha'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Desenvolver produtos alimentícios saudáveis e seguros, utilizando matéria prima de origem orgânica que não agridam o meio ambiente, sem adição de conservantes ou produtos químicos, para garantir a saúde de todas as pessoas, desde bebes até a fase adulta objetivando uma vida saudável, além da harmonia com o meio ambiente.'
, 'Alimento e Bebida'
, 'www.emporiodapapinha.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Estação Felycidade'
, 'Estação Felycidade'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/estacao_felycidade/estacao_felycidade1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/estacao_felycidade/estacao_felycidade2.jpg'
, 'Empresa de caracterização de personagens.'
, 'Entretenimento'
, 'www.estacaofelycidade.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Embalando Sonhos'
, 'Embalando Sonhos'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Embalagens para doces, bem casado, etc.Caixinhas e wrappers para cupcake. Lembrancinhas e caixas para presentes. Forminhas e porta guardanapo. Feitas em tecido ou cortadas a laser. Amêndoas italianas'
, 'Serviços e Produtos'
, ''
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Fabiana Moura'
, 'Fabiana Moura'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Projetos de decoração personalizados para eventos sociais adultos e infantis. São Paulo - SP'
, 'Decoração de Festas'
, 'm.facebook.com/FabianaMouraProjetosPersonalizados'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Fisher Price'
, 'Fisher Price'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Descubra o poder da brincadeira com a gente. Compartilhe a emoção de descobrir com seu filho e tenha dias maravilhosos!'
, 'Serviços e Produtos'
, 'm.facebook.com/FisherPriceBrasil'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Fotografilhos'
, 'Fotografilhos'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Fotografia'
, 'Serviços e Produtos'
, 'www.fotografilhos.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Funclick'
, 'Funclick'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Funclick a atração mais inovadora e interativa que irá garantir o sucesso e a repercussão do seu evento.'
, 'Serviços e Produtos'
, 'm.facebook.com/pages/Funclick/151727798197931'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Gabi Danuze Party Designer'
, 'Gabi Danuze Party Designer'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Elaboração e execução de festas personalizadas, utilizando a técnica de scrapbook, desde o convite até a lembrancinha e confeitaria personalizada e temática.'
, 'Alimento e Bebida'
, 'm.facebook.com/pages/Gabi-Danuze/136936156426300'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Gigi Luxo'
, 'Gigi Luxo'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Chupetas - Prendedores de chupeta - Pente e Escova - Quadros de maternidade '
, 'Serviços e Produtos'
, 'm.facebook.com/pages/Gigi-Luxo/371542019602433'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Glitz Mania'
, 'Glitz Mania'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O GlitzMania, primeiro salão de beleza temático do país, trouxe um novo conceito em tratamento infantil e transforma os cuidados com os cabelos em pura diversão.'
, 'Serviços e Produtos'
, 'www.glitzmania.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Green Short Doces'
, 'Green Short Doces'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Macarons Franceses'
, 'Alimento e Bebida'
, 'www.gsdoces.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ideia Única Locação'
, 'Ideia Única Locação'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/ideia_unica_locacao/ideia_unica_locacao1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/ideia_unica_locacao/ideia_unica_locacao1.jpg'
, 'A Ideia Única é uma empresa especializada em locação de objetos para festas e flores para decoração de eventos.'
, 'Serviços e Produtos'
, 'm.facebook.com/ideiaunica'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Kako Makeup'
, 'Kako Makeup'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Maquiagem'
, 'Serviços e Produtos'
, ''
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Kangulu Wrap Sling'
, 'Kangulu Wrap Sling'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O carregador wrap sling proporciona ao bebê uma agradável transição do útero para o mundo exterior. Kangulu Wrap Sling serve para qualquer tamanho de bebê, podendo ser usado desde recém nascido até crianças que pesam até 20 kgs ou enquanto for confortável para a criança e a mamãe.'
, 'Moda'
, 'www.kangulu.blogspot.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Kits e Requintes'
, 'Kits e Requintes'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Gifts para maternidade, festas infantis, eventos corporativos, casamentos e datas comemorativas.'
, 'Lembranças'
, 'www.kitserequintes.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Lansinoh'
, 'Lansinoh'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A marca número 1 em produtos para amamentação nos Estados Unidos, chega ao Brasil em 2013 com uma linha completa para auxiliar mães nessa experiência tão linda e importante que é a amamentação. Aguarde as novidades!'
, 'Serviços e Produtos'
, 'm.facebook.com/LansinohBrasil'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Lart in Dolce'
, 'Lart in Dolce'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Bolachas, bolos e dos doces esculpidos'
, 'Alimento e Bebida'
, 'm.facebook.com/lartindolce'
, 0, ''
, ''); 
INSERT INTO vitrinis VALUES('Letícia Dream Baby'
, 'Letícia Dream Baby'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Leticia Dream Baby#SocialMediaMom'
, 'Blogueiras'
, 'm.facebook.com/leticiadreambaby'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Luciana Lourenço Eventos Exclusivos'
, 'Luciana Lourenço Eventos Exclusivos'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/luciana_lourenco_eventos_exclusivos/luciana_lourenco_eventos_exclusivos1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/luciana_lourenco_eventos_exclusivos/luciana_lourenco_eventos_exclusivos2.jpg'
, ' LUCIANA LOURENÇO - FESTAS E EVENTOS EXCLUSIVOS, ESPECIALIZADA EM ORGANIZAÇÃO E DECORAÇÃO DE EVENTOS Personalizados (ANIVERSÁRIO, CHÁ DE BEBÊ, BATIZADO, CASAMENTO, COFFEE BREAK, ENTRE OUTROS...),'
, 'Decoração de Festas'
, 'www.lourencoassessoria.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Mães Brasileiras'
, 'Mães Brasileiras'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/maes_brasileiras/maes_brasileiras1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/maes_brasileiras/maes_brasileiras1.jpg'
, 'Blog formado por três Mães Brasileiras que compartilham com muito carinho e dedicação dicas e ideias para facilitar a vida das outras mamães.Vivenciamos a maternidade tanto virtualmente quanto pessoalmente e possibilitamos encontros bimestrais com evento, diversão e brincadeiras para toda a família.'
, 'Blogueiras'
, 'm.facebook.com/MaesBrasileiras'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Malu Mattos'
, 'Malu Mattos'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Malu Mattos - Ateliê de Eventos realiza sonhos e experiências repletas de satisfação e alegria! Fazemos cada festa como se fosse nossa - os detalhes são a diferença!'
, 'Decoração de Festas'
, 'www.malumattos.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Manginelli Balões'
, 'Manginelli Balões'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/manginelli_baloes/manginelli_baloes1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/manginelli_baloes/manginelli_baloes2.jpg'
, 'Decoração em Balões'
, 'Serviços e Produtos'
, ''
, 0, ''
, ''); 
INSERT INTO vitrinis VALUES('Mamãe de Primeira Viagem'
, 'Mamãe de Primeira Viagem'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/mamae_de_primeira_viagem/mamae_de_primeira_viagem1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/mamae_de_primeira_viagem/mamae_de_primeira_viagem2.jpg'
, 'A ideia desse blog surgiu em meio às inquietações, felicidade, plenitude e momentos de pânico que toda mulher enfrenta na gestação. Principalmente na primeira gestação, em que tudo é novo e desconhecido. Um misto de euforia, alegria, plenitude, medo, irritação e expectativas toma conta da gente, daí não é fácil entender e lidar com tudo isso ao mesmo tempo.'
, 'Blogueiras'
, 'www.mamaedeprimeiraviagem.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Maminforma'
, 'Maminforma'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Mami''N Forma é uma comunidade voltada para o estilo de vida das mulheres modernas, contemporâneas, que buscam aliar seus interesses profissionais, familiares e pessoais.'
, 'Blogueiras'
, 'm.facebook.com/MamiNForma'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Mammys Gestante'
, 'Mammys Gestante'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'LOJA ESPECIALIZADA EM MODA GESTANTE E NOSSA PROPOSTA É OFERECER ÀS FUTURAS MAMÃES, ROUPAS CONFORTÁVEIS E ELEGANTES, DENTRO DAS TENDÊNCIAS ATUAIS DE MODA E ESTILO.'
, 'Moda'
, 'm.facebook.com/mammysbauru'
, 0, 'Bauru'
, 'SP'); 
INSERT INTO vitrinis VALUES('Manual da Mamãe'
, 'Manual da Mamãe'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/manual_da_mamae/manual_da_mamae1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/manual_da_mamae/manual_da_mamae2.jpg'
, 'O Manual da Mamãe é um guia regional com informações, produtos e serviços para as gestantes e mamães.'
, 'Serviços e Produtos'
, 'www.manualdamamae.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Marcelo Romano'
, 'Marcelo Romano'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A gravidez é parte da natureza se manifestando, quando o fotógrafo toma esta expressão maravilhosa de vida, eternizando com a fotografia, se faz também parte dela também. A cumplicidade do fotógrafo é inevitável. Com o tempo o bebê vem ao mundo. A experiência da maternidade é tão intensa quanto rápida. Se você não se lembra de alguns detalhes de seu casamento, imagine do parto! Guardar estas recordações, mostrar a seus filhos no futuro em um belo álbum pode não ter preço. Não perca a oportunidade de eternizar esta viagem do parto, as pessoas que o ajudam a trazer o seu mundo seguro e que culmina com nascimento. Tenha o prazer de compartilhar com seus queridos familiares e amigos esta experiência única.'
, 'Serviços e Produtos'
, 'www.fotografomarcelo.wordpress.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Maria Manuela'
, 'Maria Manuela'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Após alguns anos realizando sonhos com Maria Manuela Eventos, decidimos que era hora de ter um bebê. Maria Manu nasceu numa família de festeiros e hoje compartilha cada detalhe, cada passo, cada sonho das mamães em comemorar os aninhos de seus filhos. Hoje em dia, os buffets infantis possuem tudo que você deseja, desde a comida até as atrações, por isso nosso objetivo maior é fazer algo diferente, customizado, uma festa voltada para a personalidade do seu pequenino'
, 'Decoração de Festas'
, 'm.facebook.com/mariamanuelaeventos'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Marília Amaral Rigor'
, 'Marília Amaral Rigor'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Noiva, noivo, daminhas, pajens, debutantes, madrinhas, padrinhos, formandas, entre outras ocasiões.'
, 'Moda'
, 'www.mariliaamaralrigor.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Mother Fit'
, 'Mother Fit'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Fisioterapia obstétrica, preparação para o parto, prevenção de incontinência urinária. Atividade Física personalizada respeitando as alterações da gestação. Pilates: auxilia na postura, flexibilidade, força, consciência corporal, relaxamento e respiração.'
, 'Serviços e Produtos'
, 'www.motherfit.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Nana Blanco'
, 'Nana Blanco'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Moda infantil de 0 a 8 anosDecoração e enxoval para bebês Móveis para quarto de bebês'
, 'Moda'
, 'www.nanablanco.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Natália Gibran'
, 'Natália Gibran'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Pioneira na criação de bolos em tecido, com compose de estampas e acabamentos diferenciados. Realiza curso de bolos em tecido e ficou conhecida por transferir suas técnicas e acabamentos aos seus alunos. '
, 'Lembranças'
, 'www.nataliagibran.blogspot.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Oficina Infantil'
, 'Oficina Infantil'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Oficinas de arte e artesanato para crianças em festas de aniversário.'
, 'Entretenimento'
, 'www.oficinainfantil.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Para Criança'
, 'Para Criança'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O ParaCriança tem o objetivo de levar informação do universo infantil aos pais, mães, e pessoas interessadas no que há de melhor para criança. '
, 'Blogueiras'
, 'm.facebook.com/paracrianca'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Petit Sachet'
, 'Petit Sachet'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Sachets perfumados para todas as ocasiões: aniversários, casamentos, bodas, debut, maternidade, corporativo, chás de apresentação, chás de bebê, chás de lingerie e de cozinha.'
, 'Lembranças'
, 'www.petitsachet.elo7.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('PetiteBox'
, 'PetiteBox'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A PetiteBox faz de uma caixinha surpresa uma experiência única de carinho para você e seu bebê. Acesse www.petitebox.com.br e saiba mais!'
, 'Serviços e Produtos'
, 'm.facebook.com/PetiteBox.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('RBK Fotografia'
, 'RBK Fotografia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O objetivo é fazer arte e encantar nosso cliente. Buscamos o lado criativo do registro, a expressão e o natural. A nossa intenção é surpreender você, inovando, capturando detalhes que fazem toda a diferença! Vamos retratar o inusitado, o imprevisto, o sorriso envergonhado, a careta, a gargalhada, os olhos marejados, a cara de surpresa e o olhar apaixonado!'
, 'Serviços e Produtos'
, 'www.rbkfotodigital.blogspot.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Red Gastronomia'
, 'Red Gastronomia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Com opções sofisticadas e criativas, o chef Marcelo Zanelatto imprime personalidade a seus menus, criando clássicos já conhecidos do grupo como a Caprese RED – tomate sem a pele, recheado de ricota de búfala e acompanhado de uma pipeta de pesto de manjericão –, escolha quase unânime dos clientes.'
, 'Alimento e Bebida'
, 'm.facebook.com/redgastronomia'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Roseli Mazulo'
, 'Roseli Mazulo'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Bacharel e Licenciada em Letras pela Universidade São Judas Tadeu. Atuou como secretária executiva por mais de 20 anos, quando começou a organizar eventos empresariais. Consultora e docente em cursos livres e técnicos nas áreas de Secretariado, Organização de Eventos e Cerimonial e Protocolo. Coordenadora de eventos realizados por alunos de cursos livres do Senac-SP. Idealizadora e coordenadora de eventos sociais, acadêmicos e empresariais.Professora universitária.'
, 'Serviços e Produtos'
, 'roselimazulo@gmail.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Starbar'
, 'Starbar'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Atendemos os mais variados tipos de eventos: Casamento. 15 Anos, Bodas, Batizado, Aniversário adulto e infantil, Confraternizações, Eventos empresariais e Etc.'
, 'Alimento e Bebida'
, 'www.starbar.net.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Stevia Manipulação'
, 'Stevia Manipulação'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/stevia_manipulacao/stevia_manipulacao1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/stevia_manipulacao/stevia_manipulacao2.jpg'
, 'Farmácia de Manipulação Stevia se orgulha de sua historia de mais de 30 anos.
Uma historia que tem como base a relação de confiança entre a Stevia, médicos e pacientes.
Encontrando na natureza soluções para a sua saúde!'
, 'Serviços e Produtos'
, 'm.facebook.com/Manipulacao.Stevia'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Sweet Carolina'
, 'Sweet Carolina'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Bolos decorados, cupcakes, cookies, pirulitos de chocolate, cake pops, brigadeiros e doces finos.'
, 'Alimento e Bebida'
, 'm.facebook.com/pages/SweetCarolina-The-Art-of-Cake/141830949166157'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Tati Designer'
, 'Tati Designer'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Desenvolvimento de logomarca, personalizados para o seu evento e artes em Geral para todas as ocasiões, tudo com muito carinho!'
, 'Serviços e Produtos'
, 'www.tatidesigner.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Traffô'
, 'Traffô'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Espaço para Eventos Sociais e Corporativos. Materializamos a perfeição da natureza na arte dos eventos.'
, 'Serviços e Produtos'
, 'www.traffo.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Unique Moda Festa'
, 'Unique Moda Festa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Loja especializada em vestidos, bolsas e acessórios para festas. Localizada em São Paulo-SP atende a todo o Brasil!'
, 'Moda'
, 'www.uniquemodafesta.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Verifest Foto e Vídeo'
, 'Verifest Foto e Vídeo'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/verifest_foto_e_video/verifest_foto_e_video1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/verifest_foto_e_video/verifest_foto_e_video2.jpg'
, 'Quando há o amor no que se faz, tudo fica especial! Registramos cada momento com todas suas emoções e alegrias, captando imagens inesquecíveis!!'
, 'Serviços e Produtos'
, 'www.verifest.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Welcome Baby Concierge'
, 'Welcome Baby Concierge'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/welcome_baby_concierge/welcome_baby_concierge1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/welcome_baby_concierge/welcome_baby_concierge2.jpg'
, 'Assessoria para gestantes, desde o enxoval até as primeiras comemorações do bebê!'
, 'Serviços e Produtos'
, 'www.welcomebabyconcierge.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Shine Eventos e Comunicações'
, 'Shine Eventos e Comunicações'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/shine_eventos_e_comunicacoes/shine_eventos_e_comunicacoes1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/shine_eventos_e_comunicacoes/shine_eventos_e_comunicacoes1.jpg'
, 'Somos a produtora Shine Eventos e Comunicações especializada em Assessoria de Imprensa, Artística, gerenciamento de Carreira, Shows, TV, Rádio, Mídias Gerais, Eventos Coorporativos e Festas.'
, 'Serviços e Produtos'
, 'https://www.facebook.com/pages/Shine-Eventos-e-Comunica%C3%A7%C3%B5es/102828863180896?fref=ts'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('São Paulo Cupcakes'
, 'São Paulo Cupcakes'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/sao_paulo_cupcakes/sao_paulo_cupcakes1.jpg'
, '../Vitrini/Android/assets/a_perfect_day_for_babies/vitrinis/sao_paulo_cupcakes/sao_paulo_cupcakes2.jpg'
, 'usando receitas americanas clássicas, nossos cupcakes são feitos com os melhores ingredientes locais ou de qualquer parte do planeta. com sabores para crianças e adultos, nossos cupcakes são perfeitos para celebrar momentos especiais. nossos sabores exclusivos, sazonais ou sob encomenda estão sempre disponíveis. esperamos que você os aprecie tanto o quanto nós os apreciamos!'
, 'Alimento e Bebida'
, 'www.saopaulocupcakes.com.br'
, 0, 'São Paulo'
, 'SP'); 
