INSERT INTO vitrinis VALUES('#obelonopapel'
, '#obelonopapel'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Jogos americanos descartáveis com estampas exclusivas que inspiram o dia a dia ou incrementam os momentos de festa por meio de estampas, idéias e motivos criados com exclusividade.'
, 'Complementos para casa'
, 'www.obelonopapel.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('A Companhia do Laço'
, 'A Companhia do Laço'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Com uma linha que transita entre o classico e o contemporâneo, consegue imprimir delicadeza, romantismo e charme em suas peças exclusivas de decoração, feitas artesanalmente.'
, 'Complementos para casa'
, 'm.facebook.com/acompanhiado.laco'
, 0, 'Campinas'
, 'SP'); 
INSERT INTO vitrinis VALUES('A de Aurélia'
, 'A de Aurélia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Linho puro, bordados e estampas estão presentes nestas criações com aroma, textura e desenhos delicados.'
, 'Infantil'
, 'm.facebook.com/AdeAureliaPichoun'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('A Duquesa'
, 'A Duquesa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Peças artesanais para decorações,infantil e o outras.'
, 'Infantil'
, '*'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('A&S Importadora'
, 'A&S Importadora'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Dedicada à importação e distribuição exclusiva no Brasil de marcas internacionais de renome mundial, a A&S busca constantemente marcas e produtos que transformem o trivial em algo criativo e inusitado.'
, 'Importados'
, 'www.aesimportadora.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('AC Gifts'
, 'AC Gifts'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Papelaria e Presentes'
, 'Importados'
, 'www.acgifts.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Adriana Yazbek'
, 'Adriana Yazbek'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Adriana Yazbek desenvolve luminárias escultóricas, que são peças de grande valor estético mesmo quando apagadas. Suas luminárias desempenham a função de iluminar de maneira poética, evidenciando o aspecto mágico dos objetos que iluminam.'
, 'Objetos'
, 'm.facebook.com/AtelieAdrianaYazbek'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Alexandre Stefani'
, 'Alexandre Stefani'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A necessidade do homem, desde a pré-história, em expressar-se artisticamente utilizando novos meios para a criação, invenção e apreciação estética, ao longo do tempo, revelou grandes artistas plásticos como Alexandre Stefani'
, 'Artes Plásticas'
, 'www.alexandrestefani.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Algoducci'
, 'Algoducci'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'É a mensagem que os produtos da Algoducci transmitem. Algoducci apresenta a sua primeira linha de produtos produzidos no Brasil, com design exclusivo, em tricot italiano, com fios de algodão e bambu. São mantas para quarto, porta travesseiros, almofadas, entre outros.'
, 'Têxtil'
, 'm.facebook.com/Algoducci'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Aline Maia Atelier'
, 'Aline Maia Atelier'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Originalidade. Este é o lema do Atelier Aline Maia, que desenvolve peças decorativas de cerâmica, esculturas, além de telas, etc...  Como diz a própria artista Aline, “que o amor e a alegria que tenho ao desenvolver meu trabalho acompanhe minha arte, por onde ela estiver!”'
, 'Artes Plásticas'
, 'm.facebook.com/AtelierAlineMaia'
, 0, 'Bichinho'
, 'MG'); 
INSERT INTO vitrinis VALUES('Álvaro Wolmer'
, 'Álvaro Wolmer'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Movelaria Fina.'
, 'Objetos'
, 'www.alvarowolmer.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ana Beatriz Miniaturas'
, 'Ana Beatriz Miniaturas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Ateliê Ana Beatriz Miniaturas com sua nova linha inspirada no material reciclado. Aproveitando materiais esquecidos no canto, como sobras de laser, revistas acumuladas e pedaços de madeira.'
, 'Objetos'
, 'm.facebook.com/pages/Ana-Beatriz-Miniaturas/560231270696109'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Ana Lua'
, 'Ana Lua'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'As porcelanas pintadas a mão, com cores fortes e desenhos bem humorados foram se expandindo também para outros suportes, como  lonas e tecidos, não perdendo a originalidade e o traço. São produtos coloridos e criativos para alegrar sua casa e seu dia a dia.'
, 'Design de Superfícies'
, 'www.analuaarte.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Ana Moraes'
, 'Ana Moraes'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Esculturas em arame e lata'
, 'Artes Plásticas'
, 'ana-moraes.blogspot.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Analuminio'
, 'Analuminio'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Ana Alumínio Artigos Decorativos Ltda vem revolucionando o mercado de decoraçao e utilidades em todo o país. Reciclando latas de alumínio, panelas velhas, fios telefônicos, peças automotivas sucateadas, entre outros materiais que contenham alumínio.'
, 'Objetos'
, 'www.analuminio.com.br'
, 0, 'Joinville'
, 'SC'); 
INSERT INTO vitrinis VALUES('Angela Massoni'
, 'Angela Massoni'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Linho, algodão e seda com bordados super exclusivos em almofadas e cortinas que dão um  toque de sofisticaçao aos ambientes.'
, 'Têxtil'
, 'www.angelamassoni.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Angélica dos Divinos'
, 'Angélica dos Divinos'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Buscado no interior (físico e espiritual) a linguagem do meu trabalho, resgatando as origens povoada de festividades religiosas, como procissões, folia de reis, festas juninas e do Divino. '
, 'Artesanato Contemporâneo'
, 'www.angelicadosdivinos.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('AR Porcelanas'
, 'AR Porcelanas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Porcelana feita à mão por Renata Barcelos'
, 'Objetos'
, 'm.facebook.com.br/ArPorcelanas'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Aromas e Cia'
, 'Aromas e Cia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Aromas marcam a nossa vida e tem o poder de nos proporcionar lembranças e reflexões, inspirando e aguçando sentidos únicos.'
, 'Complementos para casa'
, 'm.facebook.com/Aromasecia'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Arte Namesa'
, 'Arte Namesa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Qualidade e requinte para sua mesa ou festa em peças finas de linho puro bordadas a mão e  linha casual em algodão com estampas exclusivas.'
, 'Têxtil'
, 'www.artenamesaenxoval.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ateliê das Caixas'
, 'Ateliê das Caixas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Caixas organizadoras finas revestidas em tecido.'
, 'Complementos para casa'
, 'www.brunabarone.com.br'
, 0, 'Uberaba'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ateliê Papelada'
, 'Ateliê Papelada'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A junção do lado artístico de uma arquiteta com uma psicóloga empresária resulta na criação de produtos personalizados de papel que valorizam a identidade das crianças, adultos e empresas.'
, 'Papelaria'
, 'www.ateliepapelada.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Atelier Caiu do Céu'
, 'Atelier Caiu do Céu'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Para pequenos e grandes !! Fadas, bailarinas, principes e princesas, móbiles, para decorar com capricho  e carinho.'
, 'Infantil'
, 'm.facebook.com/AtelierCaiuDoCeu'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Atelier Viva Vovó'
, 'Atelier Viva Vovó'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Telas coloridas, pintadas a mão, onde delicadeza e bom gosto são parceiros constantes.Flores, arabescos, passarinhos...tudo para deixar os ambientes de sua casa ainda mais bonitos.Coisas de Minas, Cores de Minas.'
, 'Complementos para casa'
, '*'
, 0, 'Uberaba'
, 'MG'); 
INSERT INTO vitrinis VALUES('Atelier Daniela Saraiva'
, 'Atelier Daniela Saraiva'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Charmosas caixinhas, lixeiras, porta/trecos, baús, quadrinhos com o mesmo aspecto dos objetos antigos. Incríveis inspirações provindas de papéis de carta franceses.'
, 'Objetos'
, 'www.danielasaraiva.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Atelier Jataí'
, 'Atelier Jataí'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Atelier Jataí, nosso expositor, é um dos convidados para apresentar sua coleção de bolsas coloridas que com certeza farão o maior sucesso no mercado internacional. Confira.'
, 'Artesanato Contemporâneo'
, '*'
, 0, 'Poços de Caldas'
, 'MG'); 
INSERT INTO vitrinis VALUES('Atelier Julio Pestana'
, 'Atelier Julio Pestana'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Quadros com motivos de Minas Gerais , peças únicas sem padronização ou produção em escala, que se adequam ao seu ambiente.'
, 'Artesanato Contemporâneo'
, 'www.ateliejuliopestana.com.br'
, 0, 'Prados'
, 'MG'); 
INSERT INTO vitrinis VALUES('Atelier Luiz Fernando Machado'
, 'Atelier Luiz Fernando Machado'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Um dos grandes destaques do portfólio do Atelier é a marmorização. Essa técnica secular de pintura consiste na aplicação de tintas líquidas sobre uma superfície também líquida. Os desenhos a partir desse contato são transferidos para um papel através de um processo de impressão, criando assim o papel marmorizado em diferentes padrões e cores.'
, 'Papelaria'
, 'www.ateliermachado.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Atelier Patricia Virmond'
, 'Atelier Patricia Virmond'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Patricia Virmond é uma artista plástica curitibana que desde criança explora desenhos a mão livre. Há vinte anos dá aulas em seu atelier e comercializa suas peças únicas em Curitiba e, mais recentemente, no Brasil todo por meio de sua loja virtual. Sua atual coleção teve inspiração nas figuras do imaginário coletivo brasileiro, de Carmem Miranda às garotas da revista O Cruzeiro. Passando por Orixás e Santos brejeiros.  '
, 'Objetos'
, 'www.patriciavirmond.com.br'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Bloom Kids'
, 'Bloom Kids'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Mochilas e merendeiras com design brasileiríssimo , mas a Bloom Kids tem muito mais do que isso: com a concepção da designer gráfica Sylvie Moyen, a grife produz adesivos decorativos – embalados em tubos e facílimos de aplicar –, lousas e Mamuskas em tecido que encantam mamães e papais loucos por design.'
, 'Infantil'
, 'www.bloomkids.com.br'
, 0, 'Belo Horizonte'
, 'MG'); 
INSERT INTO vitrinis VALUES('Bordados Natividade'
, 'Bordados Natividade'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Nossos produtos são feitos com esmero, muita qualidade e acabamento impecável, unindo retalhos e bordando flores e cores da nossa região em bolsas, cintos, tiaras, necessaires, almofadas, guardanapos entre muitos outros acessórios de moda e objetos de decoração.'
, 'Artesanato Contemporâneo'
, 'www.bordadosnatividade.com.br'
, 0, 'Natividade'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Byzetto'
, 'Byzetto'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Com estilo, criatividade e muito amor, Alessandra Bizzetto desenvolve todos os acessórios da sua linha. Países como Itália, Inglaterra, Espanha, por onde morou e caminhou, influenciaram suas idéias, mas é no estimado Brail que ela realiza esse  sonho de espalhar as byzettinhas por aí...'
, 'Acessórios'
, 'www.byzetto.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Caixa Filosofal'
, 'Caixa Filosofal'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Caixa Filosofal acredita que a decoração deve refletir sua personalidade e suas emoções. Por isso transformou frases que emocionam, motivam e inspiram em lindos presentes com conteúdo.'
, 'Complementos para casa'
, 'www.caixafilosofal.com.br/lojista'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Campo Grande a Tiracolo'
, 'Campo Grande a Tiracolo'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Bolsas de lona de malotes reciclados '
, 'Sustentabilidade'
, 'www.campograndeatiracolo.com'
, 0, 'Campo Grande'
, 'MS'); 
INSERT INTO vitrinis VALUES('Carpe Diem'
, 'Carpe Diem'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Viva melhor com bolsas, ecobags, cases, moringas, cadernos e muito mais!'
, 'Acessórios'
, 'www.carpediembrasil.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Carré Cases'
, 'Carré Cases'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'São Bolsas e Cases com design funcional que além de serem usadas no dia-a-dia para trabalhar ou nos encontros sociais, estão prontas para levar com praticidade e conforto também seus gadgets, ou seja, Laptops, Tablets, Câmera Fotográfica Profissional, entre outros dispositivos em compartimentos especiais.'
, 'Acessórios'
, 'm.facebook.com/carrecases'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('CAS Brinquedos e Bichos de Pano'
, 'CAS Brinquedos e Bichos de Pano'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Coleção variada de brinquedos e bichos de pano de espécies silvestres da fauna brasileira como as coloridas aves, simpáticos mamíferos e divertidos répteis para aprender brincando.'
, 'Infantil'
, 'www.bichosdepano.com.br'
, 0, 'Jandira'
, 'SP'); 
INSERT INTO vitrinis VALUES('Casa do Oleiro'
, 'Casa do Oleiro'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Pratos em cerâmica de origem espanhola de Talavera, feito e pintado a mão, decorativo e utilitário. '
, 'Objetos'
, 'www.ceramicatalavera.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Casa Zoppi'
, 'Casa Zoppi'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Todo o luxo e a sofisticação que sua mesa merece, desde um jantar a luz de velas como também uma recepção de casamento ou bodas.'
, 'Têxtil'
, 'www.casazoppi.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Christina Cunali'
, 'Christina Cunali'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Atelier de joalheria contemporânea'
, 'Joalheria Autoral'
, 'm.facebook.com/pages/Christina-Cunali-joias-contemporaneas/318335698215670'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Cicero Papelaria'
, 'Cicero Papelaria'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Misturamos o cool e o sofisticado com a nossa obsessão pela qualidade e desenvolvemos os melhores cadernos para suas vidas. Abusamos da criatividade inventando moda, com simplicidade e conteúdo. Desejamos ser uma inspiração para estimular o pensamento, lembrando que cada página em branco é uma nova chance para fazer acontecer. '
, 'Papelaria'
, 'www.ciceropapelaria.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Cida Sanchez'
, 'Cida Sanchez'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A designer Cida Sanchez traz, para seus anéis e colares, a beleza das pedras lapidadas, a delicadeza da porcelana esmaltada e o toque suave da prata, em um mix de harmonia, simplicidade e feminilidade.'
, 'Joalheria Autoral'
, 'm.facebook.com/cida.sanchez'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Coisas da Flávia'
, 'Coisas da Flávia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Foi a partir deste conceito que a empresa Coisas da Flavia começou a desenvolver produtos que ajudam na tarefa de organizar e manter organizados armários, closets, malas e objetos, fazendo render o espaço disponível e mantendo todo seu conteúdo limpo e arrumado.'
, 'Complementos para casa'
, 'www.coisasdaflavia.com.br'
, 0, 'Ribeirão Preto'
, 'SP'); 
INSERT INTO vitrinis VALUES('Corporação de Ofícios'
, 'Corporação de Ofícios'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Corporação de Ofícios surgiu a partir do trabalho que vínhamos (Corina Wipfli + Mônica Wipfli Spinelli) desenvolvendo nas áreas de arquitetura, design, e artes plásticas, e do desejo de trabalhar com diferentes grupos de produtores.'
, 'Objetos'
, 'www.quatrovezeswipfli.blogspot.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Correio Elegante'
, 'Correio Elegante'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Os papéis ganham vida através das cores e desenhos...e nos ensinam pela graça da escrita. É este o "papel" da Correio elegante!'
, 'Infantil'
, 'www.correioelegantepapeis.blogspot.com.br'
, 0, 'Itu'
, 'SP'); 
INSERT INTO vitrinis VALUES('Cotton Cloud'
, 'Cotton Cloud'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Listas de chá de bebê e lembrancinhas para maternidade. Enxovais, acessórios e bichinhos de algodão 100% orgânico natural.'
, 'Infantil'
, 'www.cottoncloud.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Criqué Caiçara'
, 'Criqué Caiçara'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'As peças da CRIQUÉ CAIÇARA são produzidas por artesãos e artesãs que vivem na Estação Ecológica da Juréia, no litoral sul de São Paulo. Inspiradas na fauna e na flora da região, todas as peças são esculpidas e pintadas manualmente, uma a uma.'
, 'Artesanato Contemporâneo'
, 'www.issuu.com/elos/docs/catalogocriquecaicara'
, 0, 'Iguape'
, 'SP'); 
INSERT INTO vitrinis VALUES('Cris Conde'
, 'Cris Conde'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Seu estilo pode ser reconhecido “de olhos fechados”, seja na sensualidade e sutileza das formas femininas ou pelo mistério dos gatos esguios e negros - que se tornaram sua logomarca - tudo isso estampado em azulejos, louças, telas e acessórios diversos, provando as mil maneiras de usar arte, sendo para presentear, colecionar e decorar'
, 'Design de Superfícies'
, 'www.crisconde.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Cumaru Estudio de Arte e Design'
, 'Cumaru Estudio de Arte e Design'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Cumaru é um estúdio de artes plásticas, artes gráficas e design. Após duas décadas focando o seu trabalho nas artes gráficas, nos últimos anos partiu para a produção de objetos de uso cotidiano. '
, 'Pop Art'
, 'www.estudiocumaru.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dafna Edery'
, 'Dafna Edery'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Dafna herdou a paixão e os segredos das técnicas artesanais em criar carteiras, e hoje produz peças de qualidade, coloridas e práticas!'
, 'Acessórios'
, 'www.dafnaedery.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dagher'
, 'Dagher'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Produtos diferenciados e de qualidade de cama e mesa.'
, 'Têxtil'
, 'www.dagher.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Damatadecor Ateliê de criação'
, 'Damatadecor Ateliê de criação'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Atelier de criação que produz objetos de decoração e brindes sempre priorizando o artesanal e , com muitas miçangas, cristais, flores e tecidos estampados.'
, 'Complementos para casa'
, 'www.damatadecor.com.br'
, 0, 'Cotia'
, 'SP'); 
INSERT INTO vitrinis VALUES('Decor Books'
, 'Decor Books'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Cria e Produz livros de arte e cultura, com conteúdo brasileiro e para brasileiros. Percorrendo uma variedade de temas como arte individual, arte coletiva, decoração, design, paisagismo, arquitetura, esporte, fotografia, moda, entre outros.'
, 'Complementos para casa'
, 'm.facebook.com/editoradecorbooks'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Decortrico'
, 'Decortrico'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Tricô que tece imagem . Desenvolvida pelo holandês Norbertus Tielemans, a técnica consiste em tecer qualquer imagem em teares digitais, com a máxima fidelidade e a mais alta qualidade. As mantas , almofadas e capas para pufes  são produzidas individualmente, com fio soft touch, 100% acrílico e antialérgico.'
, 'Têxtil'
, ''
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Derick Objetos'
, 'Derick Objetos'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O Grande diferencial da empresa Derick Objetos está na originalidade de seus produtos, que sugerem uma aproximação com diversas linguagens. É fácil identificar a influência da arquitetura e das artes plásticas em muitas das criações.'
, 'Objetos'
, 'www.derickobjetos.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Design Possível'
, 'Design Possível'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O Design Possível é uma associação sem fins lucrativos que tem como missão utilizar as ferramentas do design para transformação social, trabalhando principalmente com projetos de geração de renda.'
, 'Sustentabilidade'
, 'www.designpossivel.org'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dona Cereja'
, 'Dona Cereja'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Dona Cereja nasceu da união de duas irmãs apaixonadas pela arte, por design, tendências e afins. O gosto por cores, estampas, e idéias fez com que a paixão se transformasse em trabalho.'
, 'Design de Superfícies'
, 'www.donacereja.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dona Emma'
, 'Dona Emma'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'As almofadas da Dona Emma trazem atmosfera de aconchego e alegria em coleções alegres e charmosas.  É tudo feito a mão com tecidos 100% algodão garantindo um toque suave e delicado.'
, 'Têxtil'
, 'www.donaemma.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dua Tecidos'
, 'Dua Tecidos'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Dua Tecidos é uma empresa de tecidos especiais impermebiliz para decoração  que desenvolve  estampas com desenhos exclusivos, despojados, coloridos, originais, arrojados, modernos, criativos e diferenciados.'
, 'Têxtil'
, 'www.duatecidos.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ducha'
, 'Ducha'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Ducha foi criada em 2003, uma marca nacional e com imagem própria direcionada para suprir a carência do mercado nacional por produtos cosméticos e acessórios voltados especificamente para o banho.  '
, 'Complementos para casa'
, 'm.facebook.com/duchacosmeticos'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Dünya Dükkan'
, 'Dünya Dükkan'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Lindas peças em cerâmica e vidro importadas que expressam fortemente a etnia turca e sua história.'
, 'Objetos'
, 'www.dunyadukkan.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Eleonora Hoshino'
, 'Eleonora Hoshino'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Após alguns anos atuando na área de arquitetura. Descobriu recentemente trabalhos voltados para decoração, como os recortes em aço carbono. Para este novo segmento de trabalho foi criada a marca "hoos".'
, 'Objetos'
, 'm.facebook.com/eleonorahoshinopecasdecorativas'
, 0, 'Botucatu'
, 'SP'); 
INSERT INTO vitrinis VALUES('Estúdio Abelha'
, 'Estúdio Abelha'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Desenvolvimento e criação de estampas corridas e localizadas, harmonias de cores, aviamentos e materiais de comunicação que são o ponto de partida para coleções de moda e decoração.'
, 'Design de Superfícies'
, 'www.estudioabelha.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Estudio Gambare'
, 'Estudio Gambare'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Pintura em porcelana.'
, 'Objetos'
, 'www.estudiogambare.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Estúdio LG'
, 'Estúdio LG'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Objetos de decoração e arte a partir de madeiras e outros elementos'
, 'Objetos'
, 'www.estudiolg.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Eurobrand'
, 'Eurobrand'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Produtos importados para papelaria e presentes'
, 'Importados'
, 'www.eurobrand.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('F Junqueira e MSP Lima'
, 'F Junqueira e MSP Lima'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Atualmente trabalha com esculturas e objetos em resina de poliéster e peças em aço e ferro soldado, utilizando material reciclado.'
, 'Objetos'
, 'www.franciscajunqueira.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Flivo Presentes'
, 'Flivo Presentes'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A empresa aposta nas estampas de pássaros e na variedade de cores para ganhar espaço no mercado. A Flivo, empresa que atua no ramo de presentes e decorações, divulga a sua nova coleção de almofadas com tema de pássaros divertidos no último trimestre do ano.'
, 'Design de Superfícies'
, 'www.flivo.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Flok Tecido Adesivo'
, 'Flok Tecido Adesivo'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Tecido adesivo impermeável e com estampas variadas e exclusivas, dentro de um novo conceito do "faça voce mesmo". Desde 2009.'
, 'Design de Superfícies'
, 'www.tecidoadesivo.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('for my guest'
, 'for my guest'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A for my guest foi criada pelo prazer de receber! Receber amigos, familiares, convidados...  Nós criamos e idealizamos cada peça e cada conceito com esse mesmo prazer e dedicação que sentimos ao receber.'
, 'Têxtil'
, 'm.facebook.com/formyguest'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Fora de Série'
, 'Fora de Série'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Artigos para crianças e adultos fora de série !'
, 'Complementos para casa'
, 'www.foradeserie.art.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Forja Recicla'
, 'Forja Recicla'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Paulo Pereira salva e recicla em sua própria oficina peças que estão sendo descartadas pela indústria e as transforma em lindos objetos de decoração.'
, 'Mobiliário'
, 'www.forjarecicla.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Galeria Gift'
, 'Galeria Gift'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Galeria atende lojas de decoração, presentes, arte e design com produtos inovadores e criativos. Levar arte ao cotidiano das pessoas através de objetos de decoração e utensílios é o principal propósito. Todos os produtos criados pela Galeria possuem design completamente exclusivo, assinados pela designer Mariana Diniz.'
, 'Objetos'
, 'www.galeriagift.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Genesio Fotografia'
, 'Genesio Fotografia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Back light, fotografias iluminadas'
, 'Artes Plásticas'
, 'www.genesiofotografia.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Gigi Luxo'
, 'Gigi Luxo'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Luxo para bebês. As linhas de chupetas, mamadeiras, prendedores, lembrancinhas são criadas e desenvolvidas para encantar!'
, 'Infantil'
, 'www.gigiluxo.com.br'
, 0, 'São Bernardo do Campo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Gilda Lacerda'
, 'Gilda Lacerda'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Arte orgânica e instintiva com elementos perpetuais, lugares decorativos e cheios de humor em quadros e peças, com cores vibrantes e luminosas.'
, 'Artes Plásticas'
, 'www.gildalacerda.com.br '
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Greghi Design'
, 'Greghi Design'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'O Designer Oswaldo Greghi Jr,  conhecido por seus objetos com estampas inusitadas, e pela consagrada artista plástica Sonia Menna Barreto, reconhecida por seu estilo único que mistura o hiper-realismo com toque de surrealismo e humor'
, 'Objetos'
, 'www.greghidesign.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Guacamole Store'
, 'Guacamole Store'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Entre uma cidade e outra atrás das perfeitas ondas mexicanas, nos deparamos com uma onda totalmente diferente: pedaços de madeira, barro e papel se transformando em lindos objetos coloridos totalmente diferentes do que já tínhamos visto.'
, 'Artes Plásticas'
, 'www.guacamolestore.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Gumii'
, 'Gumii'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A marca tem DNA escandinavo: luxuosa, moderna, descolada e já é febre entre as mamães.  Possui peças feitas no Brasil e Eua , mantendo o design inovador, lúdico e minimalista, característico dos países nórdicos. Impossível não colecionar e não usar todos os dias e a qualquer hora.'
, 'Infantil'
, 'www.hightrade.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Haus und Garten'
, 'Haus und Garten'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Localizada em Guaratinguetá, no Vale do Paraíba, a H&G conta com profissionais que possuem vasta experiência no ramo de decoração e presentes, e que irão ajudar você a encontrar o produto ideal para sua loja. Fabricamos, importamos e distribuímos uma variada linha de produtos.'
, 'Objetos'
, 'www.hghaus.com.br'
, 0, 'Guaratinguetá'
, 'SP'); 
INSERT INTO vitrinis VALUES('Henna'
, 'Henna'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Patricia Henna associa ao design de características minimalistas - formas puras, cores sólidas, síntese de informaçõ visual, a preocupação com a funcionalidade dos colares. Suas criações são feitas para usar.'
, 'Acessórios'
, 'www.hennaarteparausar.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Hocdie Design'
, 'Hocdie Design'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A HocDie traz bonecos de madeira articulados, perfeitos para qualquer decoração. São diversos bonecos articulados, e customizados para todos os gostos, as esculturas possuem representação própria, é possível encontrar robô, anjo, rei, palhaço, mergulhador, fotógrafo, Chapolin e outros.'
, 'Objetos'
, 'm.facebook.com/pages/HocDie-design/300576313341522'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Home by Odila'
, 'Home by Odila'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Jogos americanos, guardanapos e toalhas que primam pela originalidade e qualidade do acabamento, em tecidos finos e puros, como o linho e o algodão.'
, 'Têxtil'
, 'www.homebyodila.com.br'
, 0, 'Ribeirão Preto'
, 'SP'); 
INSERT INTO vitrinis VALUES('Il Casalingo'
, 'Il Casalingo'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Uniformes e objetos cotidianos para casa, inspirados em antigas formas de design.'
, 'Têxtil'
, 'www.ilcasalingo.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ilana Zimberg'
, 'Ilana Zimberg'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Ilana aposta em acessórios exclusivos que envolvem obras de artistas renomados. A marca está sempre de olho aplicando inovação em suas coleções e mantendo o conceito urbano/contemporâneo .'
, 'Acessórios'
, 'www.ilanazimberg.wordpress.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Indoor'
, 'Indoor'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Rodapé para portas.'
, 'Complementos para casa'
, 'www.rodapeindoor.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('In-feite'
, 'In-feite'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Acessórios femininos e para o lar.'
, 'Acessórios'
, 'www.in-feiteacessorios.blogspot.com.br'
, 0, 'Niterói'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Isla by Isabel Lamadrid'
, 'Isla by Isabel Lamadrid'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A fascinação da India com seus contrastes e cores servem de inspiração nos colares, brincos, pulseiras com labradonitas, rubis, ônix e outras varidades de pedras brutas e lapidadas.'
, 'Joalheria Autoral'
, 'm.Facebook.com/isla.lamadrid'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Jaya! by Sabrina Arini'
, 'Jaya! by Sabrina Arini'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Sabrina Arini, designer gráfica e ilustradora desde 2000. Trabalhou em estúdios de design e agências de publicidade. Proprietária do estúdio Jaya desde 2008, sua linha de objetos, produzidos em papelão serigrafado, também participou do projeto Destination Brazil, iniciativa do MoMA, N.Y., em 2009, para a venda de produtos brasileiros em sua loja.'
, 'Pop Art'
, 'www.jayadesign.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Kidstar'
, 'Kidstar'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Kidstar mimos para bebê. Criação de produtos para enxoval, acessórios e presentes para bebês.'
, 'Infantil'
, 'www.kidstar.art.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('kikoy''s Brasil'
, 'kikoy''s Brasil'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Panôs africanos tecidos manualmente, kikoys não é só moda é responsabilidade social'
, 'Têxtil'
, 'www.kikoys.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('L''Art Espelhos & Decoração'
, 'L''Art Espelhos & Decoração'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Molduras em resina com espelho, com infinita variedade de cores e tamanhos para decorar com elegância e criatividade qualquer ambiente.'
, 'Complementos para casa'
, 'www.lartespelhosedecoracao.blogspot.com'
, 0, 'Campinas'
, 'SP'); 
INSERT INTO vitrinis VALUES('Leka Acessórios'
, 'Leka Acessórios'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A nova tendência do mercado de acessórios'
, 'Acessórios'
, 'm.facebook.com/lekaacessorios'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('L''Envie Parfums'
, 'L''Envie Parfums'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A L`ENVIE é composta por um time de colaboradores multicultural, com relevante experiência nacional e internacional no mercado de cosmético e perfumaria. Somos apaixonados por fragrâncias. Acreditamos que as fragrâncias são representações da vida, e de tudo que faz parte dela. Almejamos a mais alta qualidade nos nossos produtos, excelência em atendimento, para que nossos clientes possam sentir o que sentimos: Paixão por fragrâncias.'
, 'Complementos para casa'
, 'm.facebook.com/pages/Lenvie-Parfums/123417674434033'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Leonardo Bueno'
, 'Leonardo Bueno'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Leonardo Bueno, designer de Maria da Fé, cidade do Sul de Minas Gerais, utiliza a madeira ecologicamente correta dos quatro cantos do mundo, descartada como resíduo e por ele transformada em peças de arte e design.'
, 'Mobiliário'
, 'm.facebook.com/LeonardoBuenoArteDesign'
, 0, 'Lage - Maria da Fé'
, 'MG'); 
INSERT INTO vitrinis VALUES('Live Trace'
, 'Live Trace'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Proutos em mdf estampado, caixotes de feira, bancos modulares, cabideros orta colares, porta trecos e revisteiros para sua casa.'
, 'Pop Art'
, 'www.livetrace.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Lúcia e Rose Romano'
, 'Lúcia e Rose Romano'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Caixas de madeira e cartonagem revestidas de tecido e transformação de sobras de materiais (madeira, papel, tecido) em peças únicas , dentro do principio da sustentabilidade.'
, 'Complementos para casa'
, 'www.luciaeroseromano.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('M2V Casa & Decoração'
, 'M2V Casa & Decoração'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A M2V Casa & Decoração tem uma proposta inovadora no Brasil, que é oferecer produtos diferenciados e exclusivos de cama, mesa, banho e decoração. Estes produtos já são encontrados nas melhores lojas do mundo. E agora a M2V Casa & Decor…'
, 'Importados'
, 'www.m2vcomercial.com.br   '
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Maison Cristal'
, 'Maison Cristal'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Marketing olfativo e linhas de produtos personalizados .'
, 'Complementos para casa'
, 'www.maisoncristal.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Margarida Bebê'
, 'Margarida Bebê'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Nossos lençóis são produzidos em pequena escala e de forma artesanal por mães empreendedoras, com tecidos e aviamentos 100% algodão, nacionais e importados. Os modelos são exclusivos, feitos em poucas unidades. Por isso, entenda se o produto que você viu e gostou se esgotou, pois a ideia é essa. Modelos novos todas as semanas. Mas vamos sugerir um outro modelo igualmente bonito e original para você.'
, 'Têxtil'
, 'www.margaridabebe.com'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Margaritá'
, 'Margaritá'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Simone Pereira busca o artesão brasileiro, compondo o trabalho de várias regiões do país e imprimindo em pequenos objetos o mundo de sonhos e imagens que trazemos dentro de nós.'
, 'Complementos para casa'
, 'm.facebook.com/MargaritaArteDecorativa'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Marília Calareso'
, 'Marília Calareso'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Luminárias e lindezas de materiais pouco usuais, com o uso de garrafas de vidro garimpadas e cúpulas estampadas e coloridas.'
, 'Objetos'
, 'www.mariliacalareso.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Marina Gaydou'
, 'Marina Gaydou'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Chic Baby Bags'
, 'Acessórios'
, 'www.marinagaydou.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Maroca'
, 'Maroca'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Marion kopel desenvolve bolsas alegres, coloridas, misturando estampas exclusivas que refletem sua personalidade estilista, que inventando o tempo inteiro, faz o que mais gosta.'
, 'Acessórios'
, 'www.marocabolsas.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Mercatto Casa'
, 'Mercatto Casa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Objetos para casa e para alma, feitas a mão desde 1999'
, 'Complementos para casa'
, 'www.mercattocasa.com.br'
, 0, 'Campinas'
, 'SP'); 
INSERT INTO vitrinis VALUES('Minhas Plantas'
, 'Minhas Plantas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Carol Costa constrói minúsculos jardins dentro de vidros artesanais, escolhendo espécies de crescimento lento e rara beleza – algumas plantas dão flores menores do que a cabeça de um alfinete. “Quero mostrar um pouco da beleza que está escondida no que resta de Mata Atlântica”, explica a jardineira, que usa muitas micro orquídeas nas peças.'
, 'Complementos para casa'
, 'www.minhasplantas.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Móbiles e outras Manufaturas'
, 'Móbiles e outras Manufaturas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Mini revoadas de pássaros, borboletas e outros. Cada móbile se torna uma peça única, já que a variedade de tecidos é infinita.'
, 'Objetos'
, 'www.mobilesmanufaturas.blogspot.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Mundo Ton Design'
, 'Mundo Ton Design'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Design em papel, objetos e têxteis.'
, 'Objetos'
, 'www.mundotondesign.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Murall Estamparia'
, 'Murall Estamparia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Estampas personalizadas.'
, 'Têxtil'
, 'www.murallestamparia.com.br'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Noblesse Obligé'
, 'Noblesse Obligé'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Objetos chiques, divertidos e com seu toque.'
, 'Complementos para casa'
, '*'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Noventa e Nove Colibris'
, 'Noventa e Nove Colibris'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Vidros e tampas em forma de sino para cobrir louças e pratos, a designer Vilma Braga desenvolveu os seus em aluminio e em cobre, os polidos e os coloridíssimos. Todos com pegador em formato de colibri.'
, 'Objetos'
, 'm.facebook.com/pages/Noventa-e-Nove-Colibris-Design/630520967010563'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ó Design'
, 'Ó Design'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Ilustrações, objetos, acessórios e brinquedos.'
, 'Objetos'
, 'www.odesignbrinquedos.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Oficina de Formas'
, 'Oficina de Formas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Em 2000, a Oficina de Formas surgiu da união da artista plástica Delly Figueiredo, a qual desde os anos 70 deu início a pinturas e posteriormente trabalhos em cerâmica, com a Design de Produtos Eduarda Figueiredo.'
, 'Artesanato Contemporâneo'
, 'www.oficinadeformas.com.br'
, 0, 'Jaboatão dos Guararapes'
, 'PE'); 
INSERT INTO vitrinis VALUES('Oficina de Ideias'
, 'Oficina de Ideias'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A união e a aplicação de tecidos de cores e formatos variados formando lindas colchas acolchoadas e almofadas em patchwork.'
, 'Têxtil'
, '*'
, 0, 'Nova Serrana'
, 'MG'); 
INSERT INTO vitrinis VALUES('Original Paper'
, 'Original Paper'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Especializada em produtos de papel, confeciona artigos para festas e eventos, brindes e presentes.Sua trajetória é marcada pela criatividade, qualidade e compromisso com seus produtos e clientes.'
, 'Papelaria'
, 'www.originalpaper.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ótima Gráfica'
, 'Ótima Gráfica'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Papelaria contemporânea e de requinte, cada linha tem um diferencial e uma característica diferente. Produção 100% in house, com alta qualidade e perfeito acabamento. Distribuidor exclusivo da Paperblanks no Brasil.'
, 'Papelaria'
, 'www.otimagrafica.com.br'
, 0, 'Pinhais'
, 'PR'); 
INSERT INTO vitrinis VALUES('P Vannucchi & M Wolff'
, 'P Vannucchi & M Wolff'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Criações que mesclam a estética contemporânea e técnicas tradicionais com produção 100% manual. A linguagem uniforme e o traço característico dão personalidade às peças , em sua maioria assinadas.'
, 'Pop Art'
, 'www.pvmw.com '
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Paleolítico'
, 'Paleolítico'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Desde 2001 a Paleolitico traz o conceito artesanal em peças decorativas, que resgatam a simplicidade e a beleza da argila em uma variada linha de produtos, como luminárias, revestimentos artesanais e cubas.'
, 'Complementos para casa'
, 'www.paleolitico.art.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Palme'
, 'Palme'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Almofadas de diferentes padronagens, formatos e tamanhos'
, 'Design de Superfícies'
, 'www.palmepillows.com'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Pano que Faço'
, 'Pano que Faço'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Fofuras feitas de Pano!'
, 'Infantil'
, 'www.panoquefaco.com.br'
, 0, 'Mogi Guaçu'
, 'SP'); 
INSERT INTO vitrinis VALUES('Panoah'
, 'Panoah'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Para os amantes da customização, a marca apresenta seus tecidos adesivados, autocolantes que podem ser aplicado em qualquer superfície lisa. Feitos em 100% algodão, você pode transformar ambientes, aplicando em paredes, repaginando móveis, forrando gavetas, cabeceiras de cama, até mesmo encapando caixas, cadernos, álbuns.'
, 'Design de Superfícies'
, 'www.panoah.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Panólatras'
, 'Panólatras'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Site de vendas de tecidos de diferentes texturas com estampas exclusivas, indicado para viciados em tecidos!'
, 'Têxtil'
, 'www.panolatras.com.br'
, 0, 'São Bernardo do Campo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Paula Pittia'
, 'Paula Pittia'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Placas para portas de maternidade, pingentes e quadros de mdf, resina e cristal, desenvolvidos com exclusividade para encantar e registrar momentos especiais. Produtos que se destacam pela beleza, sofisticação e carinho.'
, 'Infantil'
, 'm.facebook.com/pages/Paula-Pittia-Arquiteta-e-Artista-Plástica/277713812276380'
, 0, 'Limeira'
, 'SP'); 
INSERT INTO vitrinis VALUES('Paula Velloso Bijoux'
, 'Paula Velloso Bijoux'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Lâmpadas, cupcakes, pães e gaiolas são transformadas em peças irreverentes que emocionam e despertam as mais inusitadas reações. Além das coleções autorais em clima retrô, a designer também cria linhas especiais para marcas renomadas.'
, 'Acessórios'
, 'www.paulavelloso.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Pipó'
, 'Pipó'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Pipó é uma das primeiras pipocas gourmet do Brasil. Uma reinvenção deliciosamente pensada em cada detalhe para proporcionar momentos de prazer e indulgência'
, 'Complementos para casa'
, 'www.pipogourmet.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Ponto SP'
, 'Ponto SP'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Presentes, papelaria, decoração. Arte aplicada.'
, 'Objetos'
, 'm.facebook.com/ponto.sp'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Porcelana Rina Ammar'
, 'Porcelana Rina Ammar'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A loja possui produtos em porcelanas com estampas florais, tudo bem romântico e com o jeito vintage'
, 'Complementos para casa'
, 'www.porcelanarinaammar.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('PPStudio'
, 'PPStudio'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Design de interiores e paisagismo.'
, 'Mobiliário'
, 'm.facebook.com/pages/PPStudio-Interiores-Arquitetura-e-Paisagismo/259153694134815'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Preto em Branco'
, 'Preto em Branco'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Marcas, empresas e produtos conquistam as pessoas na medida em que lhes significam algo, em uma experiência que é primordialmente estética, porque a compreensão se dá através dos sentidos.'
, 'Objetos'
, 'www.lumendesign.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Printas'
, 'Printas'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Objetos para decorar, produtos para seu dia-a-dia, coisas que vão fazer parte da sua vida. Beleza, design e humor.'
, 'Objetos'
, 'www.printas.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Programa Art Paraíba'
, 'Programa Art Paraíba'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Artesanato paraibano - trabalhos em renda labirinto e renda renascença, madeira, cerâmica, fibra, couro, metal e fios.'
, 'Artesanato Contemporâneo'
, 'www.paraiba.pb.gov.br'
, 0, 'João Pessoa'
, 'PB'); 
INSERT INTO vitrinis VALUES('PurpoZ'
, 'PurpoZ'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Somos uma marca 100% brasileira que desenvolve uma linha exclusiva de almofadas ilustradas aqui mesmo e bordadas com esmero em máquinas computadorizadas, dando um toque de diferenciação nos nossos produtos. Cada uma de nossas peças tem um tema que remete ao Brasil ou a uma paixão universal, tudo feito à mão e bordado em alto relevo para garantir um produto com mais personalidade e sofisticação.'
, 'Têxtil'
, 'www.purpoz.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Roupa de Mesa'
, 'Roupa de Mesa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Roupa de mesa.'
, 'Têxtil'
, '*'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Roxy Brindes'
, 'Roxy Brindes'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Brindes corporativos exclusivos e aviamentos metálicos.'
, 'Acessórios'
, 'www.roxyshop.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Sanjô'
, 'Sanjô'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Fazendo a fantasia ganhar vida na forma de bordado , através do desenvolvimento de jogos americano , toalhas de lavabo , toalhas de mesa , porta lingerie'
, 'Têxtil'
, 'www.confeccoessanjo.com.br'
, 0, 'São João Nepomuceno'
, 'MG'); 
INSERT INTO vitrinis VALUES('Santa Frescura'
, 'Santa Frescura'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Santa Frescura produz quadros e objetos de decoração em estilo shabby chic para casa e bebê. Peças confeccionadas e pintadas manualmente com muito carinho para encantar sua loja: bandejas, kits de higiene, porta de maternidade, quadros, cabides , espelhos e acessórios.'
, 'Complementos para casa'
, 'www.santafrescura.com'
, 0, 'Campinas'
, 'SP'); 
INSERT INTO vitrinis VALUES('Santa Graça'
, 'Santa Graça'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Ateliê de decoração e moda.'
, 'Complementos para casa'
, 'www.santagracastg.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Santo Ofício'
, 'Santo Ofício'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Atelie de criação de moveis feitos com madeira de demolição e pinturas especiais. Santo Oficio e um ateliê - marcenaria que, por um profundo respeito à natureza, transforma, reaproveita e produz pecas e objetos exclusivos e de alta qualidade, somente a partir do uso de madeira proveniente de demolição de tulhas e casarões antigos.'
, 'Mobiliário'
, 'www.marcenariasantooficio.com'
, 0, 'São Carlos'
, 'SP'); 
INSERT INTO vitrinis VALUES('Seagate'
, 'Seagate'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Produtos têxteis importados e nacionais para casa'
, 'Têxtil'
, '*'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Seda France'
, 'Seda France'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Velas personalizadas.'
, 'Complementos para casa'
, 'www.kevinstore.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Sérgio Fabris'
, 'Sérgio Fabris'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Perambula entre todas as artes: Pintura, escultura, design gráfico, poesias concretas, instalações. Entrega-se a São Paulo e às suas paisagens urbanas peculiarmente, com uma técnica refinada, revelando tão bem a experiência.'
, 'Artes Plásticas'
, 'm.facebook.com/SSAtelier'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('ShofarKids'
, 'ShofarKids'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Nos céus dos brinquedos, móveis e objetos de design para crianças.'
, 'Infantil'
, 'www.shofarkids.com'
, 0, 'Curitiba'
, 'PR'); 
INSERT INTO vitrinis VALUES('Silvia Polito'
, 'Silvia Polito'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Produzindo fofuras para decorar quartos de bebês e suas festinhas. Os mais fofos desejos.'
, 'Infantil'
, 'www.silviapolito.com.br'
, 0, 'Jundiaí'
, 'SP'); 
INSERT INTO vitrinis VALUES('SkeletonLeaves'
, 'SkeletonLeaves'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Arte em folhas naturais esqueletizadas. A marca nasceu da admiração pela beleza das folhas e a vontade de eternizá-la em produtos que mostrem todo o seu encanto.'
, 'Sustentabilidade'
, 'www.skeletonleaves.com.br'
, 0, 'Mogi-Mirim'
, 'SP'); 
INSERT INTO vitrinis VALUES('Solar Iluminação'
, 'Solar Iluminação'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A lava-luz solar é uma marca original vendida desde 1999. Fabricamos com o mais alto padrão de design  e qualidade britânico'
, 'Objetos'
, 'www.lavaluz.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Stephanie Stein'
, 'Stephanie Stein'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Stephanie Stein (23 anos) nasceu e cresceu na cidade de Mogi das Cruzes, em um mundo rodeado por ouro e pedras preciosas, realidade pouco usual para uma criança comum. Filha de joalheiros observava o pai, Ademir S. Stein, trabalhar e aprendia ainda pequena, o valor de uma joia e a importância de seu processo de produção minucioso e manual.'
, 'Joalheria Autoral'
, 'www.stephaniestein.com.br'
, 0, 'Mogi das Cruzes'
, 'SP'); 
INSERT INTO vitrinis VALUES('STUDIO KHOR DESIGN'
, 'STUDIO KHOR DESIGN'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Assinado pelo designer Kleber Ramos, apresenta a ilusória linha INDUIA, móveis originais, que a primeira vista parecem contruídos em ferro rústico, mas são feitos em MDF e artesanalmente pintados para produzir esse efeito. Mesclados no equilíbrio das cores vibrantes da laca e do acrílico explorados em lindos objetos decorativos.'
, 'Objetos'
, 'www.studiokhor.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Superesinados'
, 'Superesinados'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Produtos pop art em resina : latas, cigarreiras, porta copos , capinhas I Phone.'
, 'Pop Art'
, 'www.flickr.com/seperesinados'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('SUSANA Mota'
, 'SUSANA Mota'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Esculturas de cerâmica e papel machê feitas pela designer com massa de biscuit , flores, rendas, tules, plumas. Um encanto!'
, 'Complementos para casa'
, 'www.susanamota.com.br'
, 0, 'Campinas'
, 'SP'); 
INSERT INTO vitrinis VALUES('Tacón mi casa'
, 'Tacón mi casa'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Com o tecido como protagonista da história, surge a Tacon com suas peças lúdicas para encantar e divertir!'
, 'Complementos para casa'
, 'www.tacon.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Tamtum Tecidos Especiais'
, 'Tamtum Tecidos Especiais'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Conhecida por sua estamparia digital moderna com cores e desenhos exclusivos. Almofadas, futons, pufes, móveis , projetos sob medida e tecidos especiais em diversos tipos de bases naturais e acrílicas para uso interno e externo.'
, 'Têxtil'
, 'www.tamtum.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('TattooStyle'
, 'TattooStyle'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Assinado pelo designer Kleber Ramos, apresenta a ilusória linha INDUIA, móveis originais, que a primeira vista parecem contruídos em ferro rústico, mas são feitos em MDF e artesanalmente pintados para produzir esse efeito. Mesclados no equilíbrio das cores vibrantes da laca e do acrílico explorados em lindos objetos decorativos.'
, 'Complementos para casa'
, 'www.tattoostyle.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Terralinda Atelier'
, 'Terralinda Atelier'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Em 2005 duas irmãs e uma grande amiga iniciaram um projeto social no bairro de Formoso no município de São José do Barreiro, Vale Histórico do rio Paraíba – SP, no qual ensinavam e forneciam material para que as moradoras da região pudessem produzir peças feitas de crochet e tecidos, assim surgiu o Terralinda Atelier. A parceria deu super certo e não parou de gerar frutos, hoje são cerca de 25 pessoas envolvidas no projeto e as peças já podem ser encontradas em lojas de decoração em São Paulo ou podem ser adquiridas pela internet.'
, 'Artesanato Contemporâneo'
, 'www.terralindaatelier.com'
, 0, 'São José do Barreiro'
, 'SP'); 
INSERT INTO vitrinis VALUES('Thaís Kato'
, 'Thaís Kato'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A arte milenar da dobradura aplicada em tecido, sem corte, sem costura, só dobras!'
, 'Objetos'
, 'www.thaiskato.com.br'
, 0, 'São Paulo'
, 'SP'); 
INSERT INTO vitrinis VALUES('Thé des Escrivains'
, 'Thé des Escrivains'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Arte do gesto e da troca, o famoso chá durante séculos os valores das casas e partilha. Georges-Emmanuel Morali, viajante gourmet e editor astuto, sempre trabalhou no mundo dos livros. Ele desenvolveu uma forma de criar uma relação especial entre o leitor e escrita: Escritores Chá nascidos em 1999 no Salon du Livre em Paris. Espaço de encontro, discussão e degustação, o suporte é um sucesso. Este é o nascimento de uma estrutura plural com base nos princípios de prazer e descoberta.'
, 'Papelaria'
, 'www.thedesecrivains.com.br'
, 0, 'Rio de Janeiro'
, 'RJ'); 
INSERT INTO vitrinis VALUES('Totz'
, 'Totz'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'A Totz abrange a totalidade do universo que envolve não apenas as crianças pequenas, mas toda a sua família.'
, 'Infantil'
, 'www.totz.com.br'
, 0, 'São bernardo do Campo'
, 'SP'); 
INSERT INTO vitrinis VALUES('YAAY! Muito + Presente'
, 'YAAY! Muito + Presente'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, '../Vitrini/Android/assets/craft_design_2014/craft_tela_inicial.png'
, 'Produtos cheios de carisma, que fogem do óbvio , realçam o brilho de um presente e transformam simples sorrisos nas mais diversas expressões de felicidade e surpresa.'
, 'Pop Art'
, 'www.yaay.com.br'
, 0, 'São Paulo'
, 'SP'); 
